from typing import Protocol

from src.models.vpn import VPNClient, VPNServer


class VPNRepositoryInterface(Protocol):
    def create_server(self, data: dict) -> VPNServer: ...
    def get_server(self, server_id: int) -> VPNServer | None: ...
    def list_servers(self) -> list[VPNServer]: ...
    def create_client(self, data: dict) -> VPNClient: ...
    def get_client(self, client_id: int) -> VPNClient | None: ...
    def list_clients(self, server_id: int | None = None) -> list[VPNClient]: ...
    def update_client(self, client: VPNClient, data: dict) -> VPNClient: ...
