---
app_env: prod
server:
  host: 0.0.0.0
  port: 8080
database:
  url: $env["DATABASE_URL"]
  port: $env["DATABASE_PORT"]
  name: $env["DATABASE_NAME"]
  user: $env["DATABASE_USER"]
  password: $env["DATABASE_PASSWORD"]
redis:
  host: $env["REDIS_HOST"]
  port: $env["REDIS_PORT"]
  password: $env["REDIS_PASSWORD"]
  queue_name: vpn_worker_queue
rate_limit_requests: 60
rate_limit_window_seconds: 60
