app_env: test
server:
  host: localhost
  port: 8080
  auth:
    - client_name: test_client
      client_key: test_key
database:
  url: localhost
  port: "5432"
  name: test_db
  user: test_user
  password: test_password
redis:
  host: localhost
  port: "6379"
  password: test_password
  queue_name: vpn_worker_queue_test
rate_limit_requests: 60
rate_limit_window_seconds: 60
