from typing import Protocol

from src.models.vpn import VPNClient, VPNServer


class VPNServiceInterface(Protocol):
    def setup_server(self, payload) -> VPNServer: ...
    def list_servers(self) -> list[VPNServer]: ...
    def create_client(self, payload) -> VPNClient: ...
    def list_clients(self, server_id: int | None = None) -> list[VPNClient]: ...
    def connect_client(self, client_id: int) -> VPNClient: ...
    def disconnect_client(self, client_id: int) -> VPNClient: ...
