from typing import Protocol
from typing import Any


class ISSHClient(Protocol):
    def connect(self, hostname: str, username: str, key_filename: str): ...
    def close(self): ...
    def execute_command(self, command: str): ...


class IRedisClient(Protocol):
    async def increment_with_expiry(self, key: str, expiry_seconds: int) -> int: ...
    async def produce_message(
        self, message: dict[str, Any], queue_name: str | None = None
    ) -> int: ...
    async def consume_messages(self, queue_name: str | None = None, timeout: int = 0): ...
    async def close(self): ...
